name: 'build images'

on:
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: '0 4 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mm28ajos/simple-dnssec-watchdog
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate secrets
        run: |
          if [[ -z "${{ secrets.DOCKER_USERNAME }}" || -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "🚫 DockerHub credentials not found!"
            exit 1
          fi

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=mm28ajos/simple-dnssec-watchdog:buildcache
          cache-to: type=registry,ref=mm28ajos/simple-dnssec-watchdog:buildcache,mode=max

      - name: Sync README to Docker Hub
        if: github.event_name != 'schedule'
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mm28ajos/simple-dnssec-watchdog
          readme: "./README.md"
